car_collection/authentication/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from car_collection.forms import UserLoginForm
from car_collection.models import User, db
from werkzeug.security import check_password_hash
from flask_login import login_user, logout_user, login_required


auth = Blueprint('auth', __name__, template_folder = 'auth_templates')



@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserLoginForm()
    try:
        if request.method == "POST" and form.validate_on_submit():
            email = form.email.data
            first_name = form.first_name.data
            last_name = form.last_name.data
            password = form.password.data

            user = User(email, password, first_name, last_name)

            db.session.add(user)
            db.session.commit()

            flash(f"You have successfully created a User account {email}", "user-created")

            return redirect(url_for('auth.signin'))

    except:
        raise Exception('Invalid Form Data: Please Check Your Form')

    return render_template('signup.html', form=form)


@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()
    try:
        if request.method == "POST" and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email, password)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('You were logged in successfully!', 'auth-success')
                return redirect(url_for('site.profile'))
    except:
        raise Exception("Invalid Form Data: Ya better check yer facts!")
    return render_template('signin.html', form=form)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('site.home'))

car_collection/site/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, current_user
from ..forms import CarForm
from ..models import Car, db
from ..helpers import wiki_how_generator



site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile', methods = ['GET', 'POST'])
@login_required
def profile():
    my_car = CarForm()
    try:
        if request.method == "POST" and my_car.validate_on_submit():
            make = my_car.make.data.title().strip()
            model = my_car.model.data.title().strip()
            year = my_car.year.data
            color = my_car.color.data.title().strip()
            your_mission = wiki_how_generator()
            user_token = current_user.token

            car = Car(make, model, year, color, your_mission, user_token)

            db.session.add(car)
            db.session.commit()

            return redirect(url_for('site.profile'))

    except:
        raise Exception("We aint takin that car! Try again pal!")

    user_token = current_user.token
    cars = Car.query.filter_by(user_token=user_token)

    return render_template('profile.html', form=my_car, cars=cars)

car_collection/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Car Collection API</title>
</head>
<body>

    <!-- NavBar Here -->
<nav class="ct-nav">
    <div>
        <img src="../static/images/car-pic.png" alt="Car Collection Logo">
    </div>
    
    <!-- Nav Items -->
    <div>
        <ul id="horizontal-list">
            <a href="{{ url_for('site.home') }}">
                <li>The Car Collection Project</li>
            </a>
            <a href="{{ url_for('site.home') }}">
                <li>Home</li>
            </a>

            {% if current_user.is_authenticated %}
            
            <a href="{{ url_for('site.profile') }}">
                <li>Profile</li>
            </a>
            <a href="{{ url_for('auth.logout') }}">
                <li>Log Out</li>
            </a>

            {% else %}

            <a href="{{ url_for('auth.signup') }}">
                <li>Sign Up</li>
            </a>
            <a href="{{ url_for('auth.signin') }}">
                <li>Sign In</li>
            </a>

            {% endif %}
        </ul>
    </div>
</nav>
<!-- End of Navbar -->

<!-- Create space for content from other html pages -->
{% block content %}

{% endblock content %}



<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

car_collection/templates/car_form.html
<form method = "POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="make-field">
        {{ form.make.label }}
        {{ form.make(class = "form-control", placeholder = "Enter Car Make") }}
        </fieldset>
        <fieldset id="model-field">
        {{ form.model.label }}
        {{ form.model(class = "form-control", placeholder = "Enter Car Model") }}
        </fieldset>
        <fieldset id="year-field">
        {{ form.year.label }}
        {{ form.year(class = "form-control", placeholder = "Enter Car Year") }}
        </fieldset>
        <fieldset id="color-field">
        {{ form.color.label }}
        {{ form.color(class = "form-control", placeholder = "Enter Car Color") }}
        </fieldset>
       
        {{ form.submit_button(class = "btn btn-primary btn-block") }}

    </div>
</form>

car_collection/templates/forms.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
        {{ form.email.label }}
        {{ form.email(class = "form-control", placeholder = "Email") }}
        </fieldset>
        <fieldset id="first-field">
        {{ form.first_name.label }}
        {{ form.first_name(class = "form-control", placeholder = "First Name") }}
        </fieldset>
        <fieldset id="last-field">
        {{ form.last_name.label }}
        {{ form.last_name(class = "form-control", placeholder = "Last Name") }}
        </fieldset>
        <fieldset id="pass-field">
        {{ form.password.label }}
        {{ form.password(class = "form-control", placeholder = "Password") }}
        </fieldset>

        {{ form.submit_button(class = "btn btn-primary btn-block") }}

    </div>

</form>